# Site settings
title: Qamusy | قاموسي
email: hi@qamusy.com
description: تعلم مفردات اللغة الإنجليزية # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "www.qamusy.com" # the base hostname & protocol for your site
author:
  twitter: qamusy

twitter:
  username: qamusy

logo: "img/logo.jpg"
image: "img/portfolio/2.jpg"

twitter_username: qamusy
facebook_username: qamusy
github_username: 

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
